
# Get SignalR connection info

POST http://localhost:7071/api/signalr/user/negotiate

# Join a game
POST http://localhost:7071/api/game/Foo2/join

{
    "PlayerName": "Lisa"
}

### Start a single player game

POST http://localhost:7071/api/game/Foo3/start

{
    "PlayerName": "Lisa"
}

###

POST http://localhost:7071/api/negotiate

###

GET http://localhost:7071/api/ping

###

POST http://localhost:7071/api/StartGame 
content-type: application/json

{
    "Id": "1232",
    "Name": "Lisa"
}

###

POST http://localhost:7071/api/events/ 
content-type: application/json

{
    "Id": "1232",
    "Name": "Lisa"
}

###

POST http://localhost:7071/api/BuyAnimal 
content-type: application/json

{
    "PlayerId": "player",
    "AnimalId": "AnimalId",
    "EnclosureId": "EnclosureId"
}

###

GET http://localhost:7071/api/AnimalState