
POST http://localhost:7071/api/negotiate

###

POST http://localhost:7071/api/StartGame 
content-type: application/json

{
    "Id": "1232",
    "Name": "Lisa"
}

###

POST http://localhost:7071/api/events/ 
content-type: application/json

{
    "Id": "1232",
    "Name": "Lisa"
}

###

POST http://localhost:7071/api/BuyAnimal 
content-type: application/json

{
    "PlayerId": "player",
    "AnimalId": "AnimalId",
    "EnclosureId": "EnclosureId"
}